var buildingMock = {
    extension: null,
    extensionList: {
        extensionElement: [
            {
                extensionList: null,
                identifier: "last_rprs",
                item: null,
                realValue: null,
                value: "2014"
            }
        ]
    },
    postalAddress: {
        displayId: null,
        effectiveDate: null,
        endDate: null,
        extension: null,
        extensionList: null,
        startDate: null,
        addressCategory: null,
        addressCategoryLabel: null,
        addressIdentifier: null,
        confidential: null,
        invalid: null,
        organization: null,
        person: null,
        preferred: null,
        countryCode: null,
        additionalInfo: null,
        additionalInfoOther: null,
        addressCode: null,
        addresseeName: null,
        apartment: "1",
        apartmentNumber: null,
        area: null,
        areaOther: null,
        ban: null,
        banOther: null,
        building: null,
        building2: null,
        buildingName: null,
        buildingNumber: null,
        chome: null,
        chomeOther: null,
        cityCode: null,
        cityName: "KRAKĂW (KRAKĂW-KROWODRZA)",
        cityNameOther: null,
        countyCode: null,
        countyName: "KrakĂłw",
        descriptionNumber: null,
        directionNumber: null,
        district: "KrakĂłw",
        districtCode: null,
        districtLine: null,
        floor: null,
        geographicalZoneName: null,
        go: null,
        goOther: null,
        house: "19",
        localName: null,
        nationCode: null,
        officeDistributor: null,
        phoneList: null,
        postalCode: "31-216",
        prefecture: null,
        prefectureOther: null,
        province: "0",
        provinceCode: null,
        region: "maĹopolskie",
        regionCode: null,
        residenceLine: null,
        sector: null,
        state: null,
        stateCode: null,
        street: "Jaracza Stefana",
        streetLine: null,
        streetName: null,
        streetNumber: null,
        streetNumber2: null,
        streetType: "ul.",
        taxAddress: null,
        text: null,
        type: null,
        typeLabel: null,
        inseecode: null,
        pobox: null
    },
    sumInsured: null,
    sumInsuredValuation: null,
    sumInsuredValuationLabel: null,
    constructionYear: 2010,
    floors: null,
    insuredFurnitureAmount: 4759,
    landParcel: null,
    landRegistry: null,
    surfaceArea: null
};